### ISSUE TITLE
Cannot read property 'use' of null

### ISSUE THREAD

**Issue by pdxwolfy** [wooorm/remark-lint#134]
I get this message every time I try to lint a markdown file in atom:

```
TypeError: Cannot read property 'use' of null at lint (/Users/wolfy/node_modules/remark-lint/index.js:11:7) 
at Function.use (/Users/wolfy/.atom/packages/linter-markdown/node_modules/unified/index.js:318:25) 
at /Users/wolfy/.atom/packages/linter-markdown/node_modules/unified-engine/lib/file-pipeline/configure.js:117:19 
at /Users/wolfy/.atom/packages/linter-markdown/node_modules/unified-engine/lib/configuration.js:444:7 
at Array.forEach (native) at /Users/wolfy/.atom/packages/linter-markdown/node_modules/unified-engine/lib/configuration.js:443:13 
at /Users/wolfy/.atom/packages/linter-markdown/node_modules/unified-engine/lib/configuration.js:327:5 
at /Users/wolfy/.atom/packages/linter-markdown/node_modules/vfile-find-up/index.js:135:9 at FSReqWrap.oncomplete (fs.js:123:15)
```

Suggestions?

**Comment by wooorm** [comment]
Hi! If you upgrade everything to their latest versions now, everything should work again!

Sorry about that!
