### ISSUE TITLE
Information on readme.md does not work and might be outdated

### ISSUE THREAD

**Issue by argeualcantara** [wooorm/remark-lint#161]
Ok, so I have the following setup:
package.json:
```json
"scripts": {
    "lint-md": "remark example.md -u remark-lint"
  },
"devDependencies": {
    "chai": "^3.5.0",
    "istanbul": "^0.4.5",
    "mocha": "^3.1.2",
    "mocha-jenkins-reporter": "^0.3.5",
    "prettify-xml": "^1.0.0",
    "remark-cli": "^2.1.0",
    "remark-lint": "^6.0.1",
    "sinon": "^1.17.6",
    "standard": "^8.6.0"
  },
"dependencies": {
    "debug": "^2.6.0",
    "valid-url": "^1.0.9"
  }
```

example.md:
```md
* Hello

[World][]
```
I keep getting this error:

```bash
$ remark example.md -u remark-lint

example.md
  1:1  error  TypeError: Cannot read property 'use' of null
    at lint (C:\Users\alcantaa\project\node_modules\remark-lint\index.js:11:7)
    at Function.use (C:\Users\alcantaa\project\node_modules\unified\index.js:318:25)
    at C:\Users\alcantaa\project\node_modules\unified-engine\lib\file-pipeline\configure.js:117:19
    at C:\Users\alcantaa\project\node_modules\unified-engine\lib\configuration.js:444:7
    at Array.forEach (native)
    at C:\Users\alcantaa\project\node_modules\unified-engine\lib\configuration.js:443:13
    at C:\Users\alcantaa\project\node_modules\unified-engine\lib\configuration.js:327:5
    at C:\Users\alcantaa\project\node_modules\vfile-find-up\index.js:135:9
    at FSReqWrap.oncomplete (fs.js:123:15)

× 1 error

```

**Comment by wooorm** [comment]
Your checking the picture, but there’s text below that picture as well, describing how the rest of the project is set up!

**Comment by argeualcantara** [comment]
Following the steps bellow the picture also gets me an error:

```bash
  1:1  error  Error: Loading `C:\Users\alcantaa\project\node_modules\remark-preset-lint-recommended\index.js` should give a function, not `[object Object]`
    at C:\Users\alcantaa\project\node_modules\unified-engine\lib\file-pipeline\configure.js:78:23
    at C:\Users\alcantaa\project\node_modules\unified-engine\lib\configuration.js:444:7
    at Array.forEach (native)
    at C:\Users\alcantaa\project\node_modules\unified-engine\lib\configuration.js:443:13
    at C:\Users\alcantaa\project\node_modules\unified-engine\lib\configuration.js:327:5
    at C:\Users\alcantaa\project\node_modules\vfile-find-up\index.js:135:9
    at FSReqWrap.oncomplete (fs.js:123:15)

× 1 error

```

**Comment by wooorm** [comment]
Could you show me what your doing to get this error?

**Comment by argeualcantara** [comment]
I've added remark-preset-lint-recomended config on the package.json

```
 "scripts": {
     "lint-md": "remark example.md"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "istanbul": "^0.4.5",
    "mocha": "^3.1.2",
    "mocha-jenkins-reporter": "^0.3.5",
    "prettify-xml": "^1.0.0",
    "remark-cli": "^2.1.0",
    "remark-lint": "^6.0.1",
    "remark-preset-lint-recommended": "^3.0.1",
    "sinon": "^1.17.6",
    "standard": "^8.6.0"
  },
  "remarkConfig": {
    "plugins": [
      "remark-preset-lint-recommended"
    ]
  },
```

then I run:
`npm run lint-md`

this gives me the error: `should give a function, not `[object Object]``

I'm not using a `.remarkrc` file

**Comment by wooorm** [comment]
P.S. I’m updating the screenshot to show the example!

**Comment by argeualcantara** [comment]
Yes, updating the remark-cli did the trick, thanks.
Sorry for the trouble
